#include <iostream>
#include <bits/stdc++.h>
#include<algorithm>
#include <iostream>
#include <map>
#include <unordered_map>
using namespace std;

map<string, string> province = {
        {"BI", "BIAŁYSTOK"},
        {"BIA", "Powiat białostocki"},
        {"BS", "Suwałki"},
        {"BL", "Łomża"},
        {"BAU", "powiat augustowski"},
        {"BIA", "powiat białostocki"},
        {"BBI", "powiat bielski"},
        {"BGR", "powiat grajewski"},
        {"BHA", "powiat hajnowski"},
        {"BKL", "powiat kolneński"},
        {"BMN", " powiat moniecki"},
        {"BSE", "powiat sejneński"},
        {"BSI", "powiat siemiatycki"},
        {"BSK", "powiat sokólski"},
        {"BSU", "powiat suwalski"},
        {"BWM", "powiat wysokomazowiecki"},
        {"BZA", "powiat zambrowski"},
        {"BLM", "powiat łomżyński"},

        {"CB", "Bydgoszcz"},
        {"CG", "Grudziądz"},
        {"CT", "Toruń"},
        {"CW", "Włocławek"},
        {"CAL", "powiat aleksandrowski"},
        {"CBR", "powiat brodnicki"},
        {"CBY", "powiat bydgoskii"},
        {"CCH", "powiat chełmiński"},
        {"CGD", "powiat golubsko-dobrzyński"},
        {"CGR", "powiat grudziądzki"},
        {"CIN", "powiat inowrocławski"},
        {"CLI", " powiat lipnowski"},
        {"CMG", "powiat mogileński"},
        {"CNA", "powiat nakielski"},
        {"CRA", "powiat radziejowski"},
        {"CRY", " powiat rypiński"},
        {"CSE", "powiat sępoleński"},
        {"CSW", "powiat świecki"},
        {"CTR", "powiat toruński"},
        {"CTU", "powiat tucholski"},
        {"CWA", "powiat wąbrzeski"},
        {"CWL", "powiat włocławski"},
        {"CZN", "powiat żniński"},

        {"DJ", " Jelenia Góra"},
        {"DL", "Legnica"},
        {"DB", "Wałbrzych"},
        {"DW", "Wrocław"},
        {"DBL", "powiat bolesławiecki"},
        {"DDZ", "powiat dzierżoniowski"},
        {"DGR", "powiat górowski"},
        {"DGL", "powiat głogowski"},
        {"DJA", "powiat jaworski"},
        {"DJE", "powiat jeleniogórski"},
        {"DKA", "powiat kamiennogórski"},
        {"DKL", "powiat kłodzki"},
        {"DLE", "powiat legnicki"},
        {"DLB", "powiat lubański"},
        {"DLU", "powiat lubiński"},
        {"DLW", "powiat lwówecki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},
        {"DMI", "powiat milicki"},


};